// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Prisma's CLI only loads `.env` by default; Next.js's convention (and ours)
// keeps real secrets in the gitignored `.env.local` instead.
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The CLI (migrate, db push, studio) needs a direct, non-pooled
    // connection for DDL and advisory locks — DATABASE_URL (the pgbouncer
    // pooler) only supports simple queries and is used solely by the
    // runtime PrismaClient adapter in src/lib/db.ts.
    url: process.env["DIRECT_URL"],
  },
});
